apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc-app.app-name }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.svc-app.container-port }}
    targetPort: {{ .Values.svc-app.target-port }}
  selector:
    app: {{ .Values.svc-app.app-name }}
